#!/usr/bin/env bash
# transfering a file to server susing ssh

# Check if the number of arguments is correct
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
#diaabling strict host key checking
export SSHPASS="-o StrictHostKeyChecking=no"

scp -i "$4"  "$1" "$3"@"$2" ~/
