#!/usr/bin/env bash
# transfering a file to server susing ssh

# Check if the number of arguments is correct
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
#diaabling strict host key checking
else
  scp -o StrictHostKeyChecking=no -i "$4"  "$1" "$3"@"$2" :~
fi

