#!/bin/bash
ssh ubuntu@100.26.10.15 << EOF
sudo apt update

sudo apt install ufw -y

sudo ufw enable

sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http

sudo ufw default deny incoming

sudo ufw --force enable

sudo ufw status
EOF
