#!/usr/bin/env bash
#that script intiallize a server with its configuration
cp /etc/hosts ~/hosts.new
sed ... ~/hosts.new
cp -f ~/hosts.new /etc/hosts
echo "127.0.0.2	localhost" >> /etc/hosts
echo "8.8.8.8	facebook.com" >> /etc/hosts
